using Microsoft.EntityFrameworkCore;

namespace Assignment.Models
{
    public class ITIContext : DbContext
    {
        public DbSet<Department> Departments { get; set; }
        public DbSet<Instructor> Instructors { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<Trainee> Trainees { get; set; }
        public DbSet<CrsResult> CrsResults { get; set; }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);

            optionsBuilder.UseSqlServer(@"Data Source=.;Initial Catalog=ITI_Ass_I44;
                                            Integrated Security=True;Trust Server Certificate=True");
        }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            /*base.OnModelCreating(modelBuilder);

            

            modelBuilder.Entity<Department>().HasData(
            new Department { Id = 1, Name = "Web development", ManagerName = "Christien Zarief" },
            new Department { Id = 2, Name = "UI/UX", ManagerName = "Abanoub Nabiel" },
            new Department { Id = 3, Name = "Open source", ManagerName = "Josephine Poulas" },
            new Department { Id = 4, Name = "Mobile development", ManagerName = "Samantha Lin" },
            new Department { Id = 5, Name = "Data Science", ManagerName = "Daniel Rodriguez" },
            new Department { Id = 6, Name = "Quality Assurance", ManagerName = "Sophia Patel" },
            new Department { Id = 7, Name = "Project Management", ManagerName = "Michael Johnson" },
            new Department { Id = 8, Name = "Network Engineering", ManagerName = "Liam Smith" },
            new Department { Id = 9, Name = "Cloud Computing", ManagerName = "Emily Chen" });





            modelBuilder.Entity<Course>().HasData(
            new Course { Id = 1, Name = "Introduction to Web Development", Degree = 100, MinDegree = 90, Hours = 40, DepartmentId = 1 },
            new Course { Id = 2, Name = "User Interface Design Fundamentals", Degree = 90, MinDegree = 80, Hours = 30, DepartmentId = 2 },
            new Course { Id = 3, Name = "Open Source Technologies", Degree = 95, MinDegree = 85, Hours = 35, DepartmentId = 3 },
            new Course { Id = 4, Name = "Mobile App Development", Degree = 95, MinDegree = 85, Hours = 35, DepartmentId = 4 },
            new Course { Id = 5, Name = "Introduction to Data Science", Degree = 90, MinDegree = 80, Hours = 30, DepartmentId = 5 },
            new Course { Id = 6, Name = "Software Quality Assurance", Degree = 85, MinDegree = 75, Hours = 25, DepartmentId = 6 },
            new Course { Id = 7, Name = "Project Management Fundamentals", Degree = 80, MinDegree = 70, Hours = 20, DepartmentId = 7 },
            new Course { Id = 8, Name = "Network Fundamentals", Degree = 85, MinDegree = 75, Hours = 25, DepartmentId = 8 },
            new Course { Id = 9, Name = "Cloud Computing Essentials", Degree = 90, MinDegree = 80, Hours = 30, DepartmentId = 9 },
            new Course { Id = 10, Name = "Database Management Systems", Degree = 85, MinDegree = 75, Hours = 25, DepartmentId = 1 },
            new Course { Id = 11, Name = "Cybersecurity Fundamentals", Degree = 90, MinDegree = 80, Hours = 30, DepartmentId = 2 },
            new Course { Id = 12, Name = "Artificial Intelligence Basics", Degree = 85, MinDegree = 75, Hours = 25, DepartmentId = 3 },
            new Course { Id = 13, Name = "Machine Learning Essentials", Degree = 90, MinDegree = 80, Hours = 30, DepartmentId = 4 },
            new Course { Id = 14, Name = "Big Data Analytics", Degree = 90, MinDegree = 80, Hours = 30, DepartmentId = 5 },
            new Course { Id = 15, Name = "Software Engineering Principles", Degree = 85, MinDegree = 75, Hours = 25, DepartmentId = 6 },
            new Course { Id = 16, Name = "Computer Graphics Fundamentals", Degree = 85, MinDegree = 75, Hours = 25, DepartmentId = 7 },
            new Course { Id = 17, Name = "Internet of Things (IoT) Essentials", Degree = 90, MinDegree = 80, Hours = 30, DepartmentId = 8 },
            new Course { Id = 18, Name = "Software Testing Techniques", Degree = 85, MinDegree = 75, Hours = 25, DepartmentId = 9 },
            new Course { Id = 19, Name = "Web Design Fundamentals", Degree = 80, MinDegree = 70, Hours = 20, DepartmentId = 1 },
            new Course { Id = 20, Name = "Agile Development Methodologies", Degree = 90, MinDegree = 80, Hours = 30, DepartmentId = 2 },
            new Course { Id = 21, Name = "Advanced Web Development", Degree = 95, MinDegree = 85, Hours = 35, DepartmentId = 3 },
            new Course { Id = 22, Name = "User Experience Design", Degree = 85, MinDegree = 75, Hours = 25, DepartmentId = 4 },
            new Course { Id = 23, Name = "Software Architecture", Degree = 95, MinDegree = 85, Hours = 35, DepartmentId = 5 },
            new Course { Id = 24, Name = "iOS App Development", Degree = 90, MinDegree = 80, Hours = 30, DepartmentId = 6 },
            new Course { Id = 25, Name = "Data Mining Techniques", Degree = 85, MinDegree = 75, Hours = 25, DepartmentId = 7 },
            new Course { Id = 26, Name = "Agile Project Management", Degree = 80, MinDegree = 70, Hours = 20, DepartmentId = 8 },
            new Course { Id = 27, Name = "Network Security", Degree = 90, MinDegree = 80, Hours = 30, DepartmentId = 9 },
            new Course { Id = 28, Name = "Cloud Infrastructure Management", Degree = 85, MinDegree = 75, Hours = 25, DepartmentId = 1 },
            new Course { Id = 29, Name = "Relational Database Design", Degree = 90, MinDegree = 80, Hours = 30, DepartmentId = 2 },
            new Course { Id = 30, Name = "Ethical Hacking", Degree = 85, MinDegree = 75, Hours = 25, DepartmentId = 3 });





            modelBuilder.Entity<Instructor>().HasData(
            new Instructor { Id = 1, Name = "John Doe", Image = "john.jpg", Salary = 50000, Address = "123 Main St", DepartmentId = 1, CourseId = 1 },
            new Instructor { Id = 2, Name = "Jane Smith", Image = "jane.jpg", Salary = 60000, Address = "456 Elm St", DepartmentId = 2, CourseId = 2 },
            new Instructor { Id = 3, Name = "Michael Johnson", Image = "michael.jpg", Salary = 55000, Address = "789 Oak St", DepartmentId = 3, CourseId = 3 },
            new Instructor { Id = 4, Name = "Emily Brown", Image = "emily.jpg", Salary = 52000, Address = "101 Pine St", DepartmentId = 4, CourseId = 4 },
            new Instructor { Id = 5, Name = "David Wilson", Image = "david.jpg", Salary = 58000, Address = "202 Cedar St", DepartmentId = 5, CourseId = 5 },
            new Instructor { Id = 6, Name = "Jessica Lee", Image = "jessica.jpg", Salary = 53000, Address = "303 Maple St", DepartmentId = 6, CourseId = 6 },
            new Instructor { Id = 7, Name = "Christopher Taylor", Image = "chris.jpg", Salary = 56000, Address = "404 Birch St", DepartmentId = 7, CourseId = 7 },
            new Instructor { Id = 8, Name = "Sarah Martinez", Image = "sarah.jpg", Salary = 59000, Address = "505 Walnut St", DepartmentId = 8, CourseId = 8 },
            new Instructor { Id = 9, Name = "Daniel Garcia", Image = "daniel.jpg", Salary = 54000, Address = "606 Pineapple St", DepartmentId = 9, CourseId = 9 },
            new Instructor { Id = 10, Name = "Lisa Rodriguez", Image = "lisa.jpg", Salary = 57000, Address = "707 Banana St", DepartmentId = 1, CourseId = 10 },
            new Instructor { Id = 11, Name = "Matthew Hernandez", Image = "matthew.jpg", Salary = 60000, Address = "808 Orange St", DepartmentId = 2, CourseId = 11 },
            new Instructor { Id = 12, Name = "Ashley King", Image = "ashley.jpg", Salary = 55000, Address = "909 Grape St", DepartmentId = 3, CourseId = 12 },
            new Instructor { Id = 13, Name = "Andrew Lopez", Image = "andrew.jpg", Salary = 52000, Address = "111 Lemon St", DepartmentId = 4, CourseId = 13 },
            new Instructor { Id = 14, Name = "Megan Young", Image = "megan.jpg", Salary = 58000, Address = "222 Lime St", DepartmentId = 5, CourseId = 14 },
            new Instructor { Id = 15, Name = "Kevin Hill", Image = "kevin.jpg", Salary = 53000, Address = "333 Cherry St", DepartmentId = 6, CourseId = 15 },
            new Instructor { Id = 16, Name = "Rachel Scott", Image = "rachel.jpg", Salary = 56000, Address = "444 Coconut St", DepartmentId = 7, CourseId = 16 },
            new Instructor { Id = 17, Name = "Justin Green", Image = "justin.jpg", Salary = 59000, Address = "555 Pine St", DepartmentId = 8, CourseId = 17 },
            new Instructor { Id = 18, Name = "Amanda Adams", Image = "amanda.jpg", Salary = 54000, Address = "666 Apple St", DepartmentId = 9, CourseId = 18 },
            new Instructor { Id = 19, Name = "Brandon Baker", Image = "brandon.jpg", Salary = 57000, Address = "777 Peach St", DepartmentId = 1, CourseId = 19 },
            new Instructor { Id = 20, Name = "Stephanie Carter", Image = "stephanie.jpg", Salary = 60000, Address = "888 Plum St", DepartmentId = 2, CourseId = 20 },
            new Instructor { Id = 21, Name = "Mark Flores", Image = "mark.jpg", Salary = 55000, Address = "999 Berry St", DepartmentId = 3, CourseId = 21 },
            new Instructor { Id = 22, Name = "Laura White", Image = "laura.jpg", Salary = 52000, Address = "121 Cherry St", DepartmentId = 4, CourseId = 22 },
            new Instructor { Id = 23, Name = "Jason Allen", Image = "jason.jpg", Salary = 58000, Address = "232 Grape St", DepartmentId = 5, CourseId = 23 },
            new Instructor { Id = 24, Name = "Catherine Martinez", Image = "catherine.jpg", Salary = 53000, Address = "343 Lemon St", DepartmentId = 6, CourseId = 24 },
            new Instructor { Id = 25, Name = "Ryan Adams", Image = "ryan.jpg", Salary = 56000, Address = "454 Lime St", DepartmentId = 7, CourseId = 25 },
            new Instructor { Id = 26, Name = "Rebecca Hill", Image = "rebecca.jpg", Salary = 59000, Address = "565 Cherry St", DepartmentId = 8, CourseId = 26 },
            new Instructor { Id = 27, Name = "Tyler Lewis", Image = "tyler.jpg", Salary = 54000, Address = "676 Coconut St", DepartmentId = 9, CourseId = 27 },
            new Instructor { Id = 28, Name = "Hannah Green", Image = "hannah.jpg", Salary = 57000, Address = "787 Pine St", DepartmentId = 1, CourseId = 28 },
            new Instructor { Id = 29, Name = "Jacob Baker", Image = "jacob.jpg", Salary = 60000, Address = "898 Apple St", DepartmentId = 2, CourseId = 29 },
            new Instructor { Id = 30, Name = "Olivia Taylor", Image = "olivia.jpg", Salary = 55000, Address = "909 Peach St", DepartmentId = 3, CourseId = 30 },
            new Instructor { Id = 31, Name = "John Smith", Image = "john_smith.jpg", Salary = 60000, Address = "123 Main St", DepartmentId = 1, CourseId = 1 },
            new Instructor { Id = 32, Name = "Emily Johnson", Image = "emily_johnson.jpg", Salary = 55000, Address = "456 Elm St", DepartmentId = 2, CourseId = 2 },
            new Instructor { Id = 33, Name = "Michael Williams", Image = "michael_williams.jpg", Salary = 62000, Address = "789 Oak St", DepartmentId = 3, CourseId = 3 },
            new Instructor { Id = 34, Name = "Sophia Brown", Image = "sophia_brown.jpg", Salary = 58000, Address = "101 Pine St", DepartmentId = 4, CourseId = 4 },
            new Instructor { Id = 35, Name = "William Johnson", Image = "william_johnson.jpg", Salary = 63000, Address = "111 Cedar St", DepartmentId = 5, CourseId = 5 },
            new Instructor { Id = 36, Name = "Emma Garcia", Image = "emma_garcia.jpg", Salary = 59000, Address = "222 Maple St", DepartmentId = 6, CourseId = 6 },
            new Instructor { Id = 37, Name = "Matthew Martinez", Image = "matthew_martinez.jpg", Salary = 61000, Address = "333 Walnut St", DepartmentId = 7, CourseId = 7 },
            new Instructor { Id = 38, Name = "Olivia Robinson", Image = "olivia_robinson.jpg", Salary = 60000, Address = "444 Ash St", DepartmentId = 8, CourseId = 8 },
            new Instructor { Id = 39, Name = "Daniel Clark", Image = "daniel_clark.jpg", Salary = 64000, Address = "555 Birch St", DepartmentId = 9, CourseId = 9 },
            new Instructor { Id = 40, Name = "Isabella Rodriguez", Image = "isabella_rodriguez.jpg", Salary = 58000, Address = "666 Pine St", DepartmentId = 1, CourseId = 10 },
            new Instructor { Id = 41, Name = "Alexander Lee", Image = "alexander_lee.jpg", Salary = 63000, Address = "777 Elm St", DepartmentId = 2, CourseId = 11 },
            new Instructor { Id = 42, Name = "Mia Hall", Image = "mia_hall.jpg", Salary = 59000, Address = "888 Oak St", DepartmentId = 3, CourseId = 12 },
            new Instructor { Id = 43, Name = "Ethan Young", Image = "ethan_young.jpg", Salary = 62000, Address = "999 Maple St", DepartmentId = 4, CourseId = 13 },
            new Instructor { Id = 44, Name = "Charlotte Hernandez", Image = "charlotte_hernandez.jpg", Salary = 57000, Address = "1010 Cedar St", DepartmentId = 5, CourseId = 14 },
            new Instructor { Id = 45, Name = "James Lopez", Image = "james_lopez.jpg", Salary = 61000, Address = "1111 Pine St", DepartmentId = 6, CourseId = 15 },
            new Instructor { Id = 46, Name = "Amelia King", Image = "amelia_king.jpg", Salary = 60000, Address = "1212 Elm St", DepartmentId = 7, CourseId = 16 },
            new Instructor { Id = 47, Name = "Benjamin Adams", Image = "benjamin_adams.jpg", Salary = 64000, Address = "1313 Oak St", DepartmentId = 8, CourseId = 17 },
            new Instructor { Id = 48, Name = "Sophia Clark", Image = "sophia_clark.jpg", Salary = 59000, Address = "1414 Walnut St", DepartmentId = 9, CourseId = 18 },
            new Instructor { Id = 49, Name = "Jacob Baker", Image = "jacob_baker.jpg", Salary = 63000, Address = "1515 Ash St", DepartmentId = 1, CourseId = 19 },
            new Instructor { Id = 50, Name = "Olivia Foster", Image = "olivia_foster.jpg", Salary = 57000, Address = "1616 Birch St", DepartmentId = 2, CourseId = 20 },
            new Instructor { Id = 51, Name = "Liam Gonzales", Image = "liam_gonzales.jpg", Salary = 61000, Address = "1717 Maple St", DepartmentId = 3, CourseId = 1 },
            new Instructor { Id = 52, Name = "Charlotte Hill", Image = "charlotte_hill.jpg", Salary = 60000, Address = "1818 Cedar St", DepartmentId = 4, CourseId = 2 },
            new Instructor { Id = 53, Name = "Noah Hughes", Image = "noah_hughes.jpg", Salary = 64000, Address = "1919 Pine St", DepartmentId = 5, CourseId = 3 },
            new Instructor { Id = 54, Name = "Ava Jenkins", Image = "ava_jenkins.jpg", Salary = 58000, Address = "2020 Elm St", DepartmentId = 6, CourseId = 4 },
            new Instructor { Id = 55, Name = "Michael Kelly", Image = "michael_kelly.jpg", Salary = 62000, Address = "2121 Oak St", DepartmentId = 7, CourseId = 5 },
            new Instructor { Id = 56, Name = "Emma Long", Image = "emma_long.jpg", Salary = 59000, Address = "2222 Walnut St", DepartmentId = 8, CourseId = 6 },
            new Instructor { Id = 57, Name = "Mason Mitchell", Image = "mason_mitchell.jpg", Salary = 63000, Address = "2323 Ash St", DepartmentId = 9, CourseId = 7 },
            new Instructor { Id = 58, Name = "Sophia Murphy", Image = "sophia_murphy.jpg", Salary = 57000, Address = "2424 Birch St", DepartmentId = 1, CourseId = 8 },
            new Instructor { Id = 59, Name = "William Nguyen", Image = "william_nguyen.jpg", Salary = 61000, Address = "2525 Maple St", DepartmentId = 2, CourseId = 9 },
            new Instructor { Id = 60, Name = "Amelia Patel", Image = "amelia_patel.jpg", Salary = 60000, Address = "2626 Cedar St", DepartmentId = 3, CourseId = 10 });






            modelBuilder.Entity<Trainee>().HasData(
            new Trainee { Id = 1, Name = "Emily Smith", Image = "emily_smith.jpg", Address = "123 Main St", Grade = 90, DepartmentId = 1 },
            new Trainee { Id = 2, Name = "Michael Johnson", Image = "michael_johnson.jpg", Address = "456 Elm St", Grade = 85, DepartmentId = 2 },
            new Trainee { Id = 3, Name = "Emma Williams", Image = "emma_williams.jpg", Address = "789 Oak St", Grade = 92, DepartmentId = 3 },
            new Trainee { Id = 4, Name = "Noah Brown", Image = "noah_brown.jpg", Address = "101 Pine St", Grade = 88, DepartmentId = 4 },
            new Trainee { Id = 5, Name = "Olivia Davis", Image = "olivia_davis.jpg", Address = "111 Cedar St", Grade = 91, DepartmentId = 5 },
            new Trainee { Id = 6, Name = "James Miller", Image = "james_miller.jpg", Address = "222 Maple St", Grade = 86, DepartmentId = 6 },
            new Trainee { Id = 7, Name = "Sophia Wilson", Image = "sophia_wilson.jpg", Address = "333 Walnut St", Grade = 94, DepartmentId = 7 },
            new Trainee { Id = 8, Name = "William Garcia", Image = "william_garcia.jpg", Address = "444 Ash St", Grade = 87, DepartmentId = 8 },
            new Trainee { Id = 9, Name = "Isabella Rodriguez", Image = "isabella_rodriguez.jpg", Address = "555 Birch St", Grade = 93, DepartmentId = 9 },
            new Trainee { Id = 10, Name = "Liam Martinez", Image = "liam_martinez.jpg", Address = "666 Pine St", Grade = 89, DepartmentId = 1 },
            new Trainee { Id = 11, Name = "Emma Anderson", Image = "emma_anderson.jpg", Address = "777 Elm St", Grade = 90, DepartmentId = 2 },
            new Trainee { Id = 12, Name = "Jacob Thompson", Image = "jacob_thompson.jpg", Address = "888 Oak St", Grade = 84, DepartmentId = 3 },
            new Trainee { Id = 13, Name = "Mia Moore", Image = "mia_moore.jpg", Address = "999 Maple St", Grade = 95, DepartmentId = 4 },
            new Trainee { Id = 14, Name = "Ethan Jackson", Image = "ethan_jackson.jpg", Address = "1010 Cedar St", Grade = 88, DepartmentId = 5 },
            new Trainee { Id = 15, Name = "Amelia White", Image = "amelia_white.jpg", Address = "1111 Pine St", Grade = 92, DepartmentId = 6 },
            new Trainee { Id = 16, Name = "Logan Harris", Image = "logan_harris.jpg", Address = "1212 Elm St", Grade = 86, DepartmentId = 7 },
            new Trainee { Id = 17, Name = "Ava Martin", Image = "ava_martin.jpg", Address = "1313 Oak St", Grade = 93, DepartmentId = 8 },
            new Trainee { Id = 18, Name = "Lucas Nelson", Image = "lucas_nelson.jpg", Address = "1414 Walnut St", Grade = 85, DepartmentId = 9 },
            new Trainee { Id = 19, Name = "Ella Thompson", Image = "ella_thompson.jpg", Address = "1515 Ash St", Grade = 94, DepartmentId = 1 },
            new Trainee { Id = 20, Name = "Lily Lewis", Image = "lily_lewis.jpg", Address = "1616 Birch St", Grade = 89, DepartmentId = 2 },
            new Trainee { Id = 21, Name = "Liam Hall", Image = "liam_hall.jpg", Address = "1717 Maple St", Grade = 91, DepartmentId = 3 },
            new Trainee { Id = 22, Name = "Zoe Walker", Image = "zoe_walker.jpg", Address = "1818 Cedar St", Grade = 86, DepartmentId = 4 },
            new Trainee { Id = 23, Name = "Jackson Perez", Image = "jackson_perez.jpg", Address = "1919 Pine St", Grade = 90, DepartmentId = 5 },
            new Trainee { Id = 24, Name = "Mia Harris", Image = "mia_harris.jpg", Address = "2020 Elm St", Grade = 88, DepartmentId = 6 },
            new Trainee { Id = 25, Name = "Jacob Clark", Image = "jacob_clark.jpg", Address = "2121 Oak St", Grade = 92, DepartmentId = 7 },
            new Trainee { Id = 26, Name = "Chloe Lee", Image = "chloe_lee.jpg", Address = "2222 Walnut St", Grade = 85, DepartmentId = 8 },
            new Trainee { Id = 27, Name = "Ethan Martinez", Image = "ethan_martinez.jpg", Address = "2323 Ash St", Grade = 93, DepartmentId = 9 },
            new Trainee { Id = 28, Name = "Madison Harris", Image = "madison_harris.jpg", Address = "2424 Birch St", Grade = 87, DepartmentId = 1 },
            new Trainee { Id = 29, Name = "Charlotte Thompson", Image = "charlotte_thompson.jpg", Address = "2525 Maple St", Grade = 95, DepartmentId = 2 },
            new Trainee { Id = 30, Name = "Ryan Moore", Image = "ryan_moore.jpg", Address = "2626 Cedar St", Grade = 86, DepartmentId = 3 },
            new Trainee { Id = 31, Name = "Mia Hernandez", Image = "mia_hernandez.jpg", Address = "2727 Pine St", Grade = 90, DepartmentId = 4 },
            new Trainee { Id = 32, Name = "Ethan Brown", Image = "ethan_brown.jpg", Address = "2828 Elm St", Grade = 88, DepartmentId = 5 },
            new Trainee { Id = 33, Name = "Sophia Lewis", Image = "sophia_lewis.jpg", Address = "2929 Oak St", Grade = 92, DepartmentId = 6 },
            new Trainee { Id = 34, Name = "Mason Harris", Image = "mason_harris.jpg", Address = "3030 Walnut St", Grade = 87, DepartmentId = 7 },
            new Trainee { Id = 35, Name = "Ava Gonzalez", Image = "ava_gonzalez.jpg", Address = "3131 Ash St", Grade = 94, DepartmentId = 8 },
            new Trainee { Id = 36, Name = "Michael Perez", Image = "michael_perez.jpg", Address = "3232 Birch St", Grade = 85, DepartmentId = 9 },
            new Trainee { Id = 37, Name = "Isabella Jackson", Image = "isabella_jackson.jpg", Address = "3333 Maple St", Grade = 93, DepartmentId = 1 },
            new Trainee { Id = 38, Name = "Liam Moore", Image = "liam_moore.jpg", Address = "3434 Cedar St", Grade = 89, DepartmentId = 2 },
            new Trainee { Id = 39, Name = "Charlotte Davis", Image = "charlotte_davis.jpg", Address = "3535 Pine St", Grade = 91, DepartmentId = 3 },
            new Trainee { Id = 40, Name = "Ella Rodriguez", Image = "ella_rodriguez.jpg", Address = "3636 Elm St", Grade = 86, DepartmentId = 4 },
            new Trainee { Id = 41, Name = "Lucas Martinez", Image = "lucas_martinez.jpg", Address = "3737 Oak St", Grade = 90, DepartmentId = 5 },
            new Trainee { Id = 42, Name = "Sophia Thompson", Image = "sophia_thompson.jpg", Address = "3838 Walnut St", Grade = 88, DepartmentId = 6 },
            new Trainee { Id = 43, Name = "Mason Johnson", Image = "mason_johnson.jpg", Address = "3939 Ash St", Grade = 92, DepartmentId = 7 },
            new Trainee { Id = 44, Name = "Ava Harris", Image = "ava_harris.jpg", Address = "4040 Birch St", Grade = 87, DepartmentId = 8 },
            new Trainee { Id = 45, Name = "William Martinez", Image = "william_martinez.jpg", Address = "4141 Maple St", Grade = 94, DepartmentId = 9 },
            new Trainee { Id = 46, Name = "Emma Anderson", Image = "emma_anderson.jpg", Address = "4242 Cedar St", Grade = 85, DepartmentId = 1 },
            new Trainee { Id = 47, Name = "Jacob Thompson", Image = "jacob_thompson.jpg", Address = "4343 Pine St", Grade = 93, DepartmentId = 2 },
            new Trainee { Id = 48, Name = "Mia Moore", Image = "mia_moore.jpg", Address = "4444 Elm St", Grade = 89, DepartmentId = 3 },
            new Trainee { Id = 49, Name = "Ethan Jackson", Image = "ethan_jackson.jpg", Address = "4545 Oak St", Grade = 91, DepartmentId = 4 },
            new Trainee { Id = 50, Name = "Amelia White", Image = "amelia_white.jpg", Address = "4646 Walnut St", Grade = 86, DepartmentId = 5 },
            new Trainee { Id = 51, Name = "Logan Harris", Image = "logan_harris.jpg", Address = "4747 Ash St", Grade = 90, DepartmentId = 6 },
            new Trainee { Id = 52, Name = "Ava Martin", Image = "ava_martin.jpg", Address = "4848 Birch St", Grade = 88, DepartmentId = 7 },
            new Trainee { Id = 53, Name = "Lucas Nelson", Image = "lucas_nelson.jpg", Address = "4949 Maple St", Grade = 92, DepartmentId = 8 },
            new Trainee { Id = 54, Name = "Ella Thompson", Image = "ella_thompson.jpg", Address = "5050 Cedar St", Grade = 87, DepartmentId = 9 },
            new Trainee { Id = 55, Name = "Lily Lewis", Image = "lily_lewis.jpg", Address = "5151 Pine St", Grade = 94, DepartmentId = 1 },
            new Trainee { Id = 56, Name = "Liam Hall", Image = "liam_hall.jpg", Address = "5252 Elm St", Grade = 85, DepartmentId = 2 },
            new Trainee { Id = 57, Name = "Zoe Walker", Image = "zoe_walker.jpg", Address = "5353 Oak St", Grade = 93, DepartmentId = 3 },
            new Trainee { Id = 58, Name = "Jackson Perez", Image = "jackson_perez.jpg", Address = "5454 Walnut St", Grade = 89, DepartmentId = 4 },
            new Trainee { Id = 59, Name = "Mia Harris", Image = "mia_harris.jpg", Address = "5555 Ash St", Grade = 91, DepartmentId = 5 },
            new Trainee { Id = 60, Name = "Jacob Clark", Image = "jacob_clark.jpg", Address = "5656 Birch St", Grade = 86, DepartmentId = 6 },
            new Trainee { Id = 61, Name = "Chloe Lee", Image = "chloe_lee.jpg", Address = "5757 Maple St", Grade = 90, DepartmentId = 7 },
            new Trainee { Id = 62, Name = "Ethan Martinez", Image = "ethan_martinez.jpg", Address = "5858 Cedar St", Grade = 88, DepartmentId = 8 },
            new Trainee { Id = 63, Name = "Madison Harris", Image = "madison_harris.jpg", Address = "5959 Pine St", Grade = 92, DepartmentId = 9 },
            new Trainee { Id = 64, Name = "Charlotte Thompson", Image = "charlotte_thompson.jpg", Address = "6060 Elm St", Grade = 87, DepartmentId = 1 },
            new Trainee { Id = 65, Name = "Ryan Moore", Image = "ryan_moore.jpg", Address = "6161 Oak St", Grade = 94, DepartmentId = 2 },
            new Trainee { Id = 66, Name = "Mia Hernandez", Image = "mia_hernandez.jpg", Address = "6262 Walnut St", Grade = 85, DepartmentId = 3 },
            new Trainee { Id = 67, Name = "Ethan Brown", Image = "ethan_brown.jpg", Address = "6363 Ash St", Grade = 93, DepartmentId = 4 },
            new Trainee { Id = 68, Name = "Sophia Lewis", Image = "sophia_lewis.jpg", Address = "6464 Birch St", Grade = 89, DepartmentId = 5 },
            new Trainee { Id = 69, Name = "Mason Harris", Image = "mason_harris.jpg", Address = "6565 Maple St", Grade = 91, DepartmentId = 6 },
            new Trainee { Id = 70, Name = "Ava Gonzalez", Image = "ava_gonzalez.jpg", Address = "6666 Cedar St", Grade = 86, DepartmentId = 7 },
            new Trainee { Id = 71, Name = "Michael Perez", Image = "michael_perez.jpg", Address = "6767 Pine St", Grade = 90, DepartmentId = 8 },
            new Trainee { Id = 72, Name = "Isabella Jackson", Image = "isabella_jackson.jpg", Address = "6868 Elm St", Grade = 88, DepartmentId = 9 },
            new Trainee { Id = 73, Name = "Liam Moore", Image = "liam_moore.jpg", Address = "6969 Oak St", Grade = 92, DepartmentId = 1 },
            new Trainee { Id = 74, Name = "Charlotte Davis", Image = "charlotte_davis.jpg", Address = "7070 Walnut St", Grade = 87, DepartmentId = 2 },
            new Trainee { Id = 75, Name = "Ella Rodriguez", Image = "ella_rodriguez.jpg", Address = "7171 Ash St", Grade = 94, DepartmentId = 3 },
            new Trainee { Id = 76, Name = "Lucas Martinez", Image = "lucas_martinez.jpg", Address = "7272 Birch St", Grade = 85, DepartmentId = 4 },
            new Trainee { Id = 77, Name = "Sophia Thompson", Image = "sophia_thompson.jpg", Address = "7373 Maple St", Grade = 93, DepartmentId = 5 },
            new Trainee { Id = 78, Name = "Mason Johnson", Image = "mason_johnson.jpg", Address = "7474 Cedar St", Grade = 89, DepartmentId = 6 },
            new Trainee { Id = 79, Name = "Ava Harris", Image = "ava_harris.jpg", Address = "7575 Pine St", Grade = 91, DepartmentId = 7 },
            new Trainee { Id = 80, Name = "William Martinez", Image = "william_martinez.jpg", Address = "7676 Elm St", Grade = 86, DepartmentId = 8 },
            new Trainee { Id = 81, Name = "Emma Anderson", Image = "emma_anderson.jpg", Address = "7777 Oak St", Grade = 90, DepartmentId = 9 },
            new Trainee { Id = 82, Name = "Jacob Thompson", Image = "jacob_thompson.jpg", Address = "7878 Walnut St", Grade = 88, DepartmentId = 1 },
            new Trainee { Id = 83, Name = "Mia Moore", Image = "mia_moore.jpg", Address = "7979 Ash St", Grade = 92, DepartmentId = 2 },
            new Trainee { Id = 84, Name = "Ethan Jackson", Image = "ethan_jackson.jpg", Address = "8080 Birch St", Grade = 87, DepartmentId = 3 },
            new Trainee { Id = 85, Name = "Amelia White", Image = "amelia_white.jpg", Address = "8181 Maple St", Grade = 94, DepartmentId = 4 },
            new Trainee { Id = 86, Name = "Logan Harris", Image = "logan_harris.jpg", Address = "8282 Cedar St", Grade = 85, DepartmentId = 5 },
            new Trainee { Id = 87, Name = "Ava Martin", Image = "ava_martin.jpg", Address = "8383 Pine St", Grade = 93, DepartmentId = 6 },
            new Trainee { Id = 88, Name = "Lucas Nelson", Image = "lucas_nelson.jpg", Address = "8484 Elm St", Grade = 89, DepartmentId = 7 },
            new Trainee { Id = 89, Name = "Ella Thompson", Image = "ella_thompson.jpg", Address = "8585 Oak St", Grade = 91, DepartmentId = 8 },
            new Trainee { Id = 90, Name = "Lily Lewis", Image = "lily_lewis.jpg", Address = "8686 Walnut St", Grade = 86, DepartmentId = 9 },
            new Trainee { Id = 91, Name = "Liam Hall", Image = "liam_hall.jpg", Address = "8787 Ash St", Grade = 90, DepartmentId = 1 },
            new Trainee { Id = 92, Name = "Zoe Walker", Image = "zoe_walker.jpg", Address = "8888 Birch St", Grade = 88, DepartmentId = 2 },
            new Trainee { Id = 93, Name = "Jackson Perez", Image = "jackson_perez.jpg", Address = "8989 Maple St", Grade = 92, DepartmentId = 3 },
            new Trainee { Id = 94, Name = "Mia Harris", Image = "mia_harris.jpg", Address = "9090 Cedar St", Grade = 87, DepartmentId = 4 });






            modelBuilder.Entity<CrsResult>().HasData(
            new CrsResult { Id = 1, Degree = 80, CourseId = 1, TraineeId = 1 },
            new CrsResult { Id = 2, Degree = 82, CourseId = 2, TraineeId = 2 },
            new CrsResult { Id = 3, Degree = 85, CourseId = 3, TraineeId = 3 },
            new CrsResult { Id = 4, Degree = 79, CourseId = 4, TraineeId = 4 },
            new CrsResult { Id = 5, Degree = 81, CourseId = 5, TraineeId = 5 },
            new CrsResult { Id = 6, Degree = 83, CourseId = 6, TraineeId = 6 },
            new CrsResult { Id = 7, Degree = 86, CourseId = 7, TraineeId = 7 },
            new CrsResult { Id = 8, Degree = 88, CourseId = 8, TraineeId = 8 },
            new CrsResult { Id = 9, Degree = 90, CourseId = 9, TraineeId = 9 },
            new CrsResult { Id = 10, Degree = 88, CourseId = 10, TraineeId = 10 },
            new CrsResult { Id = 11, Degree = 86, CourseId = 11, TraineeId = 11 },
            new CrsResult { Id = 12, Degree = 84, CourseId = 12, TraineeId = 12 },
            new CrsResult { Id = 13, Degree = 82, CourseId = 13, TraineeId = 13 },
            new CrsResult { Id = 14, Degree = 80, CourseId = 14, TraineeId = 14 },
            new CrsResult { Id = 15, Degree = 78, CourseId = 15, TraineeId = 15 },
            new CrsResult { Id = 16, Degree = 85, CourseId = 16, TraineeId = 16 },
            new CrsResult { Id = 17, Degree = 83, CourseId = 17, TraineeId = 17 },
            new CrsResult { Id = 18, Degree = 81, CourseId = 18, TraineeId = 18 },
            new CrsResult { Id = 19, Degree = 79, CourseId = 19, TraineeId = 19 },
            new CrsResult { Id = 20, Degree = 77, CourseId = 20, TraineeId = 20 },

            new CrsResult { Id = 21, Degree = 85, CourseId = 1, TraineeId = 21 },
            new CrsResult { Id = 22, Degree = 78, CourseId = 2, TraineeId = 22 },
            new CrsResult { Id = 23, Degree = 84, CourseId = 3, TraineeId = 23 },
            new CrsResult { Id = 24, Degree = 81, CourseId = 4, TraineeId = 24 },
            new CrsResult { Id = 25, Degree = 80, CourseId = 5, TraineeId = 25 },
            new CrsResult { Id = 26, Degree = 82, CourseId = 6, TraineeId = 26 },
            new CrsResult { Id = 27, Degree = 85, CourseId = 7, TraineeId = 27 },
            new CrsResult { Id = 28, Degree = 78, CourseId = 8, TraineeId = 28 },
            new CrsResult { Id = 29, Degree = 84, CourseId = 9, TraineeId = 29 },
            new CrsResult { Id = 30, Degree = 81, CourseId = 10, TraineeId = 30 },
            new CrsResult { Id = 31, Degree = 80, CourseId = 11, TraineeId = 31 },
            new CrsResult { Id = 32, Degree = 82, CourseId = 12, TraineeId = 32 },
            new CrsResult { Id = 33, Degree = 85, CourseId = 13, TraineeId = 33 },
            new CrsResult { Id = 34, Degree = 78, CourseId = 14, TraineeId = 34 },
            new CrsResult { Id = 35, Degree = 84, CourseId = 15, TraineeId = 35 },
            new CrsResult { Id = 36, Degree = 81, CourseId = 16, TraineeId = 36 },
            new CrsResult { Id = 37, Degree = 80, CourseId = 17, TraineeId = 37 },
            new CrsResult { Id = 38, Degree = 82, CourseId = 18, TraineeId = 38 },
            new CrsResult { Id = 39, Degree = 85, CourseId = 19, TraineeId = 39 },
            new CrsResult { Id = 40, Degree = 78, CourseId = 20, TraineeId = 40 },

            new CrsResult { Id = 41, Degree = 84, CourseId = 1, TraineeId = 41 },
            new CrsResult { Id = 42, Degree = 81, CourseId = 2, TraineeId = 42 },
            new CrsResult { Id = 43, Degree = 80, CourseId = 3, TraineeId = 43 },
            new CrsResult { Id = 44, Degree = 82, CourseId = 4, TraineeId = 44 },
            new CrsResult { Id = 45, Degree = 85, CourseId = 5, TraineeId = 45 },
            new CrsResult { Id = 46, Degree = 78, CourseId = 6, TraineeId = 46 },
            new CrsResult { Id = 47, Degree = 84, CourseId = 7, TraineeId = 47 },
            new CrsResult { Id = 48, Degree = 81, CourseId = 8, TraineeId = 48 },
            new CrsResult { Id = 49, Degree = 80, CourseId = 9, TraineeId = 49 },
            new CrsResult { Id = 50, Degree = 82, CourseId = 10, TraineeId = 50 },
            new CrsResult { Id = 51, Degree = 85, CourseId = 11, TraineeId = 51 },
            new CrsResult { Id = 52, Degree = 78, CourseId = 12, TraineeId = 52 },
            new CrsResult { Id = 53, Degree = 84, CourseId = 13, TraineeId = 53 },
            new CrsResult { Id = 54, Degree = 81, CourseId = 14, TraineeId = 54 },
            new CrsResult { Id = 55, Degree = 80, CourseId = 15, TraineeId = 55 },
            new CrsResult { Id = 56, Degree = 82, CourseId = 16, TraineeId = 56 },
            new CrsResult { Id = 57, Degree = 85, CourseId = 17, TraineeId = 57 },
            new CrsResult { Id = 58, Degree = 78, CourseId = 18, TraineeId = 58 },
            new CrsResult { Id = 59, Degree = 84, CourseId = 19, TraineeId = 59 },
            new CrsResult { Id = 60, Degree = 81, CourseId = 20, TraineeId = 60 },

            new CrsResult { Id = 61, Degree = 80, CourseId = 1, TraineeId = 61 },
            new CrsResult { Id = 62, Degree = 82, CourseId = 2, TraineeId = 62 },
            new CrsResult { Id = 63, Degree = 85, CourseId = 3, TraineeId = 63 },
            new CrsResult { Id = 64, Degree = 78, CourseId = 4, TraineeId = 64 },
            new CrsResult { Id = 65, Degree = 84, CourseId = 5, TraineeId = 65 },
            new CrsResult { Id = 66, Degree = 81, CourseId = 6, TraineeId = 66 },
            new CrsResult { Id = 67, Degree = 80, CourseId = 7, TraineeId = 67 },
            new CrsResult { Id = 68, Degree = 82, CourseId = 8, TraineeId = 68 },
            new CrsResult { Id = 69, Degree = 85, CourseId = 9, TraineeId = 69 },
            new CrsResult { Id = 70, Degree = 78, CourseId = 10, TraineeId = 70 },
            new CrsResult { Id = 71, Degree = 84, CourseId = 11, TraineeId = 71 },
            new CrsResult { Id = 72, Degree = 81, CourseId = 12, TraineeId = 72 },
            new CrsResult { Id = 73, Degree = 80, CourseId = 13, TraineeId = 73 },
            new CrsResult { Id = 74, Degree = 82, CourseId = 14, TraineeId = 74 },
            new CrsResult { Id = 75, Degree = 85, CourseId = 15, TraineeId = 75 },
            new CrsResult { Id = 76, Degree = 78, CourseId = 16, TraineeId = 76 },
            new CrsResult { Id = 77, Degree = 84, CourseId = 17, TraineeId = 77 },
            new CrsResult { Id = 78, Degree = 81, CourseId = 18, TraineeId = 78 },
            new CrsResult { Id = 79, Degree = 80, CourseId = 19, TraineeId = 79 },
            new CrsResult { Id = 80, Degree = 82, CourseId = 20, TraineeId = 80 },

            new CrsResult { Id = 81, Degree = 85, CourseId = 1, TraineeId = 81 },
            new CrsResult { Id = 82, Degree = 78, CourseId = 2, TraineeId = 82 },
            new CrsResult { Id = 83, Degree = 84, CourseId = 3, TraineeId = 83 },
            new CrsResult { Id = 84, Degree = 81, CourseId = 4, TraineeId = 84 },
            new CrsResult { Id = 85, Degree = 80, CourseId = 5, TraineeId = 85 },
            new CrsResult { Id = 86, Degree = 82, CourseId = 6, TraineeId = 86 },
            new CrsResult { Id = 87, Degree = 85, CourseId = 7, TraineeId = 87 },
            new CrsResult { Id = 88, Degree = 78, CourseId = 8, TraineeId = 88 },
            new CrsResult { Id = 89, Degree = 84, CourseId = 9, TraineeId = 89 },
            new CrsResult { Id = 90, Degree = 81, CourseId = 10, TraineeId = 90 },
            new CrsResult { Id = 91, Degree = 80, CourseId = 11, TraineeId = 91 },
            new CrsResult { Id = 92, Degree = 82, CourseId = 12, TraineeId = 92 },
            new CrsResult { Id = 93, Degree = 85, CourseId = 13, TraineeId = 93 },
            new CrsResult { Id = 94, Degree = 78, CourseId = 14, TraineeId = 94 },
            new CrsResult { Id = 95, Degree = 84, CourseId = 15, TraineeId = 81 },
            new CrsResult { Id = 96, Degree = 81, CourseId = 16, TraineeId = 92 },
            new CrsResult { Id = 97, Degree = 80, CourseId = 17, TraineeId = 65 },
            new CrsResult { Id = 98, Degree = 82, CourseId = 18, TraineeId = 82 },
            new CrsResult { Id = 99, Degree = 85, CourseId = 19, TraineeId = 63 },
            new CrsResult { Id = 100, Degree = 78, CourseId = 20, TraineeId = 86 },

            new CrsResult { Id = 101, Degree = 78, CourseId = 1, TraineeId = 39 },
            new CrsResult { Id = 102, Degree = 84, CourseId = 2, TraineeId = 94 },
            new CrsResult { Id = 103, Degree = 81, CourseId = 3, TraineeId = 76 },
            new CrsResult { Id = 104, Degree = 80, CourseId = 4, TraineeId = 64 },
            new CrsResult { Id = 105, Degree = 82, CourseId = 5, TraineeId = 13 },
            new CrsResult { Id = 106, Degree = 85, CourseId = 6, TraineeId = 42 },
            new CrsResult { Id = 107, Degree = 78, CourseId = 7, TraineeId = 53 },
            new CrsResult { Id = 108, Degree = 84, CourseId = 8, TraineeId = 43 },
            new CrsResult { Id = 109, Degree = 81, CourseId = 9, TraineeId = 93 },
            new CrsResult { Id = 110, Degree = 80, CourseId = 10, TraineeId = 10 },
            new CrsResult { Id = 111, Degree = 82, CourseId = 11, TraineeId = 11 },
            new CrsResult { Id = 112, Degree = 85, CourseId = 12, TraineeId = 12 },
            new CrsResult { Id = 113, Degree = 78, CourseId = 13, TraineeId = 13 },
            new CrsResult { Id = 114, Degree = 84, CourseId = 14, TraineeId = 14 },
            new CrsResult { Id = 115, Degree = 81, CourseId = 15, TraineeId = 15 },
            new CrsResult { Id = 116, Degree = 80, CourseId = 16, TraineeId = 16 },
            new CrsResult { Id = 117, Degree = 82, CourseId = 17, TraineeId = 17 },
            new CrsResult { Id = 118, Degree = 85, CourseId = 18, TraineeId = 18 },
            new CrsResult { Id = 119, Degree = 78, CourseId = 19, TraineeId = 19 },
            new CrsResult { Id = 120, Degree = 84, CourseId = 20, TraineeId = 20 },

            new CrsResult { Id = 121, Degree = 81, CourseId = 1, TraineeId = 11 },
            new CrsResult { Id = 122, Degree = 80, CourseId = 2, TraineeId = 12 },
            new CrsResult { Id = 123, Degree = 82, CourseId = 3, TraineeId = 13 },
            new CrsResult { Id = 124, Degree = 85, CourseId = 4, TraineeId = 14 },
            new CrsResult { Id = 125, Degree = 78, CourseId = 5, TraineeId = 15 },
            new CrsResult { Id = 126, Degree = 84, CourseId = 6, TraineeId = 16 },
            new CrsResult { Id = 127, Degree = 81, CourseId = 7, TraineeId = 17 },
            new CrsResult { Id = 128, Degree = 80, CourseId = 8, TraineeId = 18 },
            new CrsResult { Id = 129, Degree = 82, CourseId = 9, TraineeId = 19 },
            new CrsResult { Id = 130, Degree = 85, CourseId = 10, TraineeId = 10 },
            new CrsResult { Id = 131, Degree = 78, CourseId = 11, TraineeId = 11 },
            new CrsResult { Id = 132, Degree = 84, CourseId = 12, TraineeId = 12 },
            new CrsResult { Id = 133, Degree = 81, CourseId = 13, TraineeId = 13 },
            new CrsResult { Id = 134, Degree = 80, CourseId = 14, TraineeId = 14 },
            new CrsResult { Id = 135, Degree = 82, CourseId = 15, TraineeId = 15 },
            new CrsResult { Id = 136, Degree = 85, CourseId = 16, TraineeId = 16 },
            new CrsResult { Id = 137, Degree = 78, CourseId = 17, TraineeId = 17 },
            new CrsResult { Id = 138, Degree = 84, CourseId = 18, TraineeId = 18 },
            new CrsResult { Id = 139, Degree = 81, CourseId = 19, TraineeId = 19 },
            new CrsResult { Id = 140, Degree = 80, CourseId = 20, TraineeId = 10 });

            */

        }
    }
}
